name: Build on Commit

on:
 - push

jobs:
    mvn:
        uses: netcracker/qubership-workflow-hub/.github/workflows/maven-publish.yml@main
        with:
            maven-command: "--batch-mode deploy -Dgpg.skip=true org.sonarsource.scanner.maven:sonar-maven-plugin:5.0.0.4389:sonar -Dsonar.projectKey=Netcracker_qubership-core-error-handling -Dsonar.organization=netcracker -Dsonar.host.url=https://sonarcloud.io -Dsonar.coverage.jacoco.xmlReportPaths='../core-error-handling-rest/target/jacoco-ut/jacoco.xml,../core-error-handling-runtime/target/jacoco-ut/jacoco.xml'"
            server-id: github
            java-version: 21
        secrets:
            maven-token: ${{ secrets.GITHUB_TOKEN }}
            sonar-token: ${{ secrets.SONAR_TOKEN }}
